### PR TITLE
Fix the scale factors for the fractal noises

### LINKED ISSUE #243: Scale Factor calculations are incorrect
Some time after the 0.7 release, something broke the billow generator. The examples which make use of it, such as slime and granite, look absolutely nothing like they did in 0.7 or in libnoise. I'm not sure what is the problem yet...been debugging for a while now. I'll post back if I find time to dive any deeper.

### PR DESCRIPTION
**Pull request by Razaekel**
Closes #243

### CODE REVIEW

**Comment by smessmer** [comment]
Is this going to be merged? I'm seeing values outside of `[-1, 1]` in the `Fbm` generator on version 0.8.1.

**Comment by smessmer** [comment]
@Razaekel This PR is necessary for me to get predictable values within [-1, 1] from the `Fbm` generator. Are you planning to merge this?

**Comment by smessmer** [comment]
Thank you :)

**Comment by PrinceOfBorgo** [comment]
I noticed that the constructor of Fbm uses the old implementation of `calc_scale_factor` (the global one) instead of the one introduced with these changes (i.e. `Self::calc_scale_factor`). I added the fix in #342 with other improvements

**Pull request merged**
